develop
charapennikaurm/files_java pull request #1
Opened 2020-10-15 13:51 UTC by charapennikaurm

2020-10-21 17:17 UTC, VeronikaYastr requested changes

2020-10-21 17:17 UTC, VeronikaYastr commented on src/main/java/com/bsu/Company.java
> +
Обычно еще добавляют методы equals, hashCode

2020-10-21 17:17 UTC, VeronikaYastr commented on src/main/java/com/bsu/CompanyReader.java
> +        File file = new File(filepath);
Мне кажется вот тут исключение может вылететь

2020-10-21 17:17 UTC, VeronikaYastr commented on src/main/java/com/bsu/CompanyReader.java
> +        try (Scanner scanner = new Scanner(file);) {
Лучше конечно это в мэйне делать или в каком-то еще классе. Вряд ли класс Company должен знать, как считывать что-то из файла

2020-10-21 17:17 UTC, VeronikaYastr commented on src/main/java/com/bsu/CompanyReader.java
> +        actualizationDate = LocalDate.parse(fields[2], formatter);
Тут на parse может исключение вылететь

2020-10-21 17:17 UTC, VeronikaYastr commented on src/main/java/com/bsu/Main.java
> +        if (request == 1) {
Лучше switch-case использовать. И enum вместо цифр🙂

2020-10-21 17:17 UTC, VeronikaYastr commented on src/main/java/com/bsu/Main.java
> +            for (Company company : companies) {
Было бы лучше, если бы был отдельный класс с методами отдельными для обработки запросов.

2020-10-21 17:17 UTC, VeronikaYastr commented on src/main/java/com/bsu/Main.java
> +            LocalDate lb = LocalDate.parse(date, formatter);
Тут при парсинге опять же может быть ошибка. Лучше обернуть в try-catch и выкидывать новое исключение, если что-то словилось

2020-10-21 17:17 UTC, VeronikaYastr commented on src/main/java/com/bsu/Main.java
> +            int ub = scanner.nextInt();
Аналогично может быть ошибка парсинга

2020-10-21 17:21 UTC, charapennikaurm commented on src/main/java/com/bsu/CompanyReader.java
> +        try (Scanner scanner = new Scanner(file);) {
это же метод другого класса (Сompany Reader), а не Company

2020-10-29 05:25 UTC, VeronikaYastr commented on src/main/java/com/bsu/CompanyReader.java
> +        try (Scanner scanner = new Scanner(file);) {
Тогда ок)

2020-11-26 06:05 UTC, merged